version: "3"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: data
    container_name: data-api
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    environment:
      XDEBUG_CONFIG: client_host=172.17.0.1
      DEBUG: 1
    working_dir: /var/www
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: data-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d

  nginx:
    image: nginx:alpine
    container_name: data-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    depends_on:
      - app    